import esbuild from 'esbuild';
import { copyFileSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'fs';
import { dirname } from 'path';

const isWatch = process.argv.includes('--watch');
const securityEntryEnabled = process.env.SECURITY_ENTRY_ENABLED !== 'false';
const securityEntryPath = securityEntryEnabled ? normalizeRequiredEntryPath(process.env.SECURITY_ENTRY_PATH) : '';
const securityEntryConfig = {
  enabled: securityEntryEnabled,
  entryPath: securityEntryPath,
  denyPaths: securityEntryEnabled ? normalizeOptionalDenyPaths(process.env.SECURITY_DENY_PATHS, securityEntryPath) : [],
};

const errorPage = {
  code: '404',
  title: 'Not Found',
  message: 'The requested resource could not be located. The address may be invalid, incomplete, or no longer available.',
};

rmSync('dist', { recursive: true, force: true });
mkdirSync('dist', { recursive: true });

const buildOptions = {
  entryPoints: ['src/app.js'],
  bundle: true,
  outfile: 'dist/app.js',
  target: ['es2020'],
  format: 'iife',
  minify: !isWatch,
  sourcemap: isWatch ? 'inline' : false,
  define: {
    __SECURITY_ENTRY_CONFIG__: JSON.stringify(securityEntryConfig),
  },
};

try {
  if (isWatch) {
    const ctx = await esbuild.context(buildOptions);
    await ctx.watch();
    console.log('Watching for changes... (Ctrl+C to stop)');
    copyStaticAssets(); // copy once at start for dev server
  } else {
    await esbuild.build(buildOptions);
    console.log('Build complete.');
    copyStaticAssets();
  }
} catch (err) {
  console.error('Build failed:', err.message);
  process.exit(1);
}

function copyStaticAssets() {
  const required = ['style.css', 'manifest.json', 'error.js'];
  const optional = [];

  for (const file of required) {
    copyFileSync(file, `dist/${file}`);
  }
  writeEntryPage();
  writeDenyPages();
  writeRootPage();
  writeErrorPage();
  writeHeaders();
  writeRedirects();
  for (const file of optional) {
    if (existsSync(file)) {
      copyFileSync(file, `dist/${file}`);
    } else {
      console.warn(`Warning: optional asset "${file}" not found, skipping.`);
    }
  }
  console.log('Static assets copied.');
}

function writeHeaders() {
  let headers = existsSync('_headers') ? readFileSync('_headers', 'utf8') : '';
  if (securityEntryConfig.enabled) {
    headers += `\n/__secure_entry\n  Content-Type: text/html; charset=utf-8\n`;
    headers += `\n${securityEntryConfig.entryPath}\n  Content-Type: text/html; charset=utf-8\n`;
    for (const path of securityEntryConfig.denyPaths) {
      headers += `\n${path}\n  Content-Type: text/html; charset=utf-8\n`;
    }
  }
  writeFileSync('dist/_headers', headers);
}

function writeEntryPage() {
  if (!securityEntryConfig.enabled) return;

  copyFileSync('index.html', 'dist/__secure_entry');
}

function writeDenyPages() {
  if (!securityEntryConfig.enabled) return;

  const html = renderErrorPage();
  for (const path of securityEntryConfig.denyPaths) {
    const denyFile = `dist/${path.slice(1)}`;
    mkdirSync(dirname(denyFile), { recursive: true });
    writeFileSync(denyFile, html);
  }
}

function writeRootPage() {
  if (!securityEntryConfig.enabled) {
    copyFileSync('index.html', 'dist/index.html');
    return;
  }

  writeFileSync('dist/index.html', renderErrorPage());
}

function writeErrorPage() {
  writeFileSync('dist/404.html', renderErrorPage());
}

function renderErrorPage() {
  return readFileSync('error.html', 'utf8')
    .replaceAll('__ERROR_CODE__', errorPage.code)
    .replaceAll('__ERROR_TITLE__', errorPage.title)
    .replaceAll('__ERROR_MESSAGE__', errorPage.message);
}

function writeRedirects() {
  if (!securityEntryConfig.enabled) {
    const redirects = [
      '# Cloudflare Pages routes.',
      '# Generated by build.js with SECURITY_ENTRY_ENABLED=false.',
      '/* /index.html 200',
      '',
    ].join('\n');
    writeFileSync('dist/_redirects', redirects);
    return;
  }

  const entryPath = securityEntryConfig.entryPath;
  const redirects = [
    '# Cloudflare Pages route gate.',
    '# Generated by build.js from SECURITY_ENTRY_PATH.',
    ...securityEntryConfig.denyPaths.map((path) => `${path} /404.html 404`),
    ...securityEntryConfig.denyPaths.map((path) => `${path}/ /404.html 404`),
    `${entryPath} /__secure_entry 200`,
    `${entryPath}/ ${entryPath} 308`,
    '/ /404.html 404',
    '/* /404.html 404',
    '',
  ].join('\n');
  writeFileSync('dist/_redirects', redirects);
}

function normalizeRequiredEntryPath(value) {
  const path = String(value || '').trim();
  if (!path || path === '/') {
    throw new Error('SECURITY_ENTRY_PATH must be set to a non-root path when SECURITY_ENTRY_ENABLED is not false.');
  }
  if (path.includes('?') || path.includes('#') || path.includes('\\') || path.split('/').includes('..')) {
    throw new Error('SECURITY_ENTRY_PATH must be a URL path without query, hash, backslash, or parent directory segments.');
  }
  const withLeadingSlash = path.startsWith('/') ? path : `/${path}`;
  return withLeadingSlash.replace(/\/+$/, '');
}

function normalizeOptionalDenyPaths(value, entryPath) {
  return String(value || '')
    .split(',')
    .map((path) => path.trim())
    .filter(Boolean)
    .map(normalizeRequiredEntryPath)
    .filter((path) => path !== entryPath);
}
